### ISSUE TITLE
getDataValue return empty string.

### ISSUE THREAD

**Issue by tien-vo-xuan** [KristianKarl-zz/GraphWalker#10]
In the out-edge of the Start vertex in mother-graph, I label it:
e_StartBrowser/books_in_cart_not_logged_in=0;books_in_cart_logged_in=0;books_in_wishlist=0;logged_in=false;books_interested=7;current_book=0;

In e_StartBrowser function in Amazon.java, I read value using:
String booksInterested = getMbt().getDataValue("books_interested");
but booksInterested is always empty string.

**Comment by KristianKarl-zz** [comment]
Hi,
I verified that it actually works.
I may have a guess why it did not work for you. If you are using eclipse to run the above test, remember to refresh the the graphml file in the eclipse project tree view. Eclipse does not do that automatically for files loaded outside itself.
