### ISSUE TITLE
unable to launch graphwalker

### ISSUE THREAD

**Issue by lakshmishub** [KristianKarl-zz/GraphWalker#15]
just downloaded the graphwalker jar file.

when i double click, get the message " could not find main class"...

**Comment by KristianKarl-zz** [comment]
Ok, let's run a check list to help me understand:
1) Download from http://graphwalker.org/data/uploads/graphwalker.jar
2) If you type from the command line: java -jar graphwalker.jar
    What do you get?
3) Pending on which OS you are using, and settings, the behavior of "double-clicking" jar files may be different. But, there's a main class in graphwalker.jar.  The manifest files states: org.graphwalker.CLI

**Comment by lakshmishub** [comment]
Nice to hear from the master of the application...

I will try these out and let you know

Regards,
Lakshmi 

Sent from iPhone..Please excuse brevity and typos 

On Dec 23, 2013, at 3:11 PM, Kristian Karl notifications@github.com wrote:

Ok, let's run a check list to help me understand:
1) Download from http://graphwalker.org/data/uploads/graphwalker.jar
2) If you type from the command line: java -jar graphwalker.jar
What do you get?
3) Pending on which OS you are using, and settings, the behavior of "double-clicking" jar files may be different. But, there's a main class in graphwalker.jar. The manifest files states: org.graphwalker.CLI

**Comment by lakshmishub** [comment]
Hi Christian,
I get " type " Java -jar graphwLkwr.jar help " for usage ...

I am trying this on a different machine...

When I double click nothing happens 

Windows 7 
32 bit
Latest jre ( downloaded a week ago ) 

Regards,
Lakshmi 

Sent from iPhone..Please excuse brevity and typos 

On Dec 23, 2013, at 3:11 PM, Kristian Karl notifications@github.com wrote:

Ok, let's run a check list to help me understand:
1) Download from http://graphwalker.org/data/uploads/graphwalker.jar
2) If you type from the command line: java -jar graphwalker.jar
What do you get?
3) Pending on which OS you are using, and settings, the behavior of "double-clicking" jar files may be different. But, there's a main class in graphwalker.jar. The manifest files states: org.graphwalker.CLI

**Comment by KristianKarl-zz** [comment]
So the output you get from command line indicates that java is installed and the download of graphwalker is ok.

Double-clicking on graphwalker is perhaps pointless, because it will do nothing useful.
Plz have a look at:
http://graphwalker.org/documentation/workflow-this-is-how-you-would-work-using-graphwalker
http://graphwalker.org/documentation/demo
for how to use graphwalker

**Comment by lakshmishub** [comment]
Cool thx... Will try it out...

Appreciate ur time...

Btw my wife pointed out that I had addresses u as "Christian":-(...sorry about it 

Regards,
Lakshmi 

Sent from iPhone..Please excuse brevity and typos 

On Dec 24, 2013, at 4:22 PM, Kristian Karl notifications@github.com wrote:

So the output you get from command line indicates that java is installed and the download of graphwalker is ok.

Double-clicking on graphwalker is perhaps pointless, because it will do nothing useful.
Plz have a look at:
http://graphwalker.org/documentation/workflow-this-is-how-you-would-work-using-graphwalker
http://graphwalker.org/documentation/demo
for how to use graphwalker

**Comment by KristianKarl-zz** [comment]
Ha ha, np :-)

**Comment by KristianKarl-zz** [comment]
Kristian Karl sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/19bf65a2-aed1-4096-831b-2f0cd03f3cd9

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Unsubscribe: https://twitter.com/i/o?t=1&iid=707e034865b241438f6dcf2f832dff8b&uid=0&c=IuVwbCB3dgGwaUZiM92%2BmMyNhj4XUBauGosGiLKk2uhNk0Tc7lcHowrE%2B8KyU8iObqS6LhWTcE1TdyemMPKmGI6nhmD5OwfIRSSC65KyyQT15kAtkiIcgQ%3D%3D&nid=9+26

Need help?
https://support.twitter.com
