### ISSUE TITLE
http://graphwalker.org/license/ - link is broken

### ISSUE THREAD

**Issue by aendinalt** [KristianKarl-zz/GraphWalker#21]
Hi Karl,

I've noticed that http://graphwalker.org/license/ link is broken.

Thanks, Aen.

**Comment by KristianKarl-zz** [comment]
I understand. But is there any page linking to that broken link.
The old link is http://graphwalker.org/old_site/license/
For the new site, the license is in every page footer. 
Maybe we should have a specific page that talks about the license. I think that makes sense.

**Comment by KristianKarl-zz** [comment]
Fixed by https://github.com/GraphWalker/graphwalker.org/commit/8d3155091a841b079ab3c8e07db722a7a7fcc202 and https://github.com/GraphWalker/graphwalker.org/commit/0e470b62c4c9ad3d08b5020d6812176dcc2fbdaf

**Comment by aendinalt** [comment]
https://github.com/KristianKarl/GraphWalker#license - here an occurrence of those broken link.
Sorry for confusing.

**Comment by KristianKarl-zz** [comment]
Np, thanx for reporting!
