### ISSUE TITLE
RESTFUL methods Reload, getStatistics and passRequirement

### ISSUE THREAD

**Issue by helmfridsson** [KristianKarl-zz/GraphWalker#22]
This method need to work when you run in -s RESTFUL (-r) mode

**Comment by KristianKarl-zz** [comment]
I'll start working on it

**Comment by KristianKarl-zz** [comment]
Fixed: 7c9f190e1ab86881efc7274e3a56ddd73844e816

**Comment by KristianKarl-zz** [comment]
Wrong github repo
