### ISSUE TITLE
Limitations of Javascript in Graphwalker

### ISSUE THREAD

**Issue by Sigurthorb** [KristianKarl-zz/GraphWalker#23]
Hello

I have been using Graphwalker for a while now and mostly as a user rather than a developer.
We have created a test case generation tool around Graphwalker and have been using it to create some complex models.

Currently I have a model where I need to take together a summary of a test case generation within the model and from this summary do some filtering. For this I though It would be perfect to use the javascript functionality of edges. 

example:
We are creating a model where we are defining columns of a SQL table with a model. It is suppose to generate a path which will be translated into a SQL query. A requirement is that for each SQL query we need to come up with a description of the query. 
Instead of having to parse the SQL query afterwards I would like to generate the description dynamically while generating the test case.
Here I decided to pick the javascript functionality to build array of objects each defining it own column of the table. 

Here I would like to be able to take full advantage of javascript but found my self only being able to use basic functionality (assign values to variables, defining arrays).

When trying to use for loops to go through array expected everything before the first semicolon in the for loop to be a statement on its own. Unable to create functions with more than one expression and so on.

Is there some documentation on what attributes of javascript can be used within Graphwalker or is this all suppose to be possible or may I just have found a bug?

(Sorry for the bad example, hope the use case of javascript in the example shows its light)

**Comment by KristianKarl-zz** [comment]
Just a quick question. Are you using graphwalker as provided by [graphwalker.org](graphwalker.org)?
Reason for me asking is, if it's so, you should go here instead: [https://github.com/GraphWalker/graphwalker-project](https://github.com/GraphWalker/graphwalker-project)

I think you might have found a bug. Please submit a bug to [https://github.com/GraphWalker/graphwalker-project](https://github.com/GraphWalker/graphwalker-project) with a model that shows the problem.

A disclaimer though. It sounds to me that you found a way to use GraphWalker in a way we did not anticipate or expect, so there might better solutions to your problem.

**Comment by Sigurthorb** [comment]
Yes, That is correct. I am using graphwalker.org library.
I will move over to that project. thank you
