### ISSUE TITLE
Executing common path for each test case 

### ISSUE THREAD

**Issue by psg123** [KristianKarl-zz/GraphWalker#24]
![try](https://user-images.githubusercontent.com/31530634/29956619-d7f3d270-8f05-11e7-99de-84f88063b043.png)

Hello Sir,

I have attached the graph and output I am getting , I am expecting the output for second condition as 

v_HomePage
e_LoginFail
v_errorpage
v_accpage
v_accpage123

Could you please help me and let me know what am I doing wrong.

**Comment by KristianKarl-zz** [comment]
Hi,
I'm not quite sure what you mean with "output for second condition".
But I guess that you expected `v_accpage123` to be visited as well at the end of the generated path?

The stop condition `edge_coverage(100)` prevents that from happening, since when reaching the vertex `v_accpage` the second time, the stop condition is fulfilled. All edges are by now covered.

Without changing the model, you could try adding an additional generator. This will start execute when the first generator's stop condition gets fulfilled. 
```
quick_random(edge_coverage(100)) a_star(reached_vertex(v_accpage123))
```

**Comment by psg123** [comment]
![try1](https://user-images.githubusercontent.com/31530634/29957346-9e418400-8f0a-11e7-8452-9658178cc74f.png)
Looks like I am still doing something wrong

**Comment by KristianKarl-zz** [comment]
No ampersand character, and no single quotes in reached_vertex condition. Like this:
```
quick_random(edge_coverage(100)) a_star(reached_vertex(v_accpage123))
```

**Comment by psg123** [comment]
When I run I get error Was passed main parameter a_star(reached_vertex(v_accpage1223)) but no main parameter was defined
![try2](https://user-images.githubusercontent.com/31530634/29958523-c610f1ae-8f10-11e7-8c5f-d67a7be41068.png)

**Comment by psg123** [comment]
how can I use all_path_permutations generator in this case

**Comment by KristianKarl-zz** [comment]
You need to enclose the generators with double quotes.

**Comment by KristianKarl-zz** [comment]
Have you had a look at http://graphwalker.org

**Comment by psg123** [comment]
Hello Sir,

All_Path_Permutations is not listed in generators http://graphwalker.github.io/generators_and_stop_conditions/ 

Is it not supported in graphwalker-cli-3.4.2?

Could you please guide me on how we can generate all paths ?

**Comment by KristianKarl-zz** [comment]
The generators available are the ones listed in the documentation at http://graphwalker.github.io/generators_and_stop_conditions/

Also. this is not the official repo. That's here: https://github.com/GraphWalker/graphwalker-project

General questions are better posted here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/graphwalker-3

Best Kristian
