### ISSUE TITLE
Unable to convert model

### ISSUE THREAD

**Issue by invertednz** [KristianKarl-zz/GraphWalker#6]
When following the Demo (http://graphwalker.org/democ) I am unable to run the command java -jar graphwalker-2.5.15-standalone.jar source -f UC01.graphml -t ModelAPI.template.  It returns the errors listed below.

I am using the latest graphwalker build graphwalker-2.5.18-SNAPSHOT-standalone.

The model template from https://github.com/KristianKarl/GraphWalker/blob/master/src/test/resources/templates/ModelAPI.template

The graph from https://github.com/KristianKarl/GraphWalker-Examples/edit/master/src/main/resources/model/ShoppingCart.graphml

Any ideas on why these errors would occur?

2012-07-30 16:47:05,690 [main] INFO  - Done merging
2012-07-30 16:47:09,113 [Thread-0] INFO  - Edge not reached: Edge: 'e_About', INDEX=10
Edge not reached: Edge: 'e_About', INDEX=13
Edge not reached: Edge: 'e_About', INDEX=19
Edge not reached: Edge: 'e_EnterBaseURL', INDEX=9
Edge not reached: Edge: 'e_Faq', INDEX=11
Edge not reached: Edge: 'e_Faq', INDEX=12
Edge not reached: Edge: 'e_Faq', INDEX=18
Edge not reached: Edge: 'e_Home', INDEX=20
Edge not reached: Edge: 'e_Regex_Search', INDEX=14
Edge not reached: Edge: 'e_Regex_Search', INDEX=15
Edge not reached: Edge: 'e_StartBrowser', INDEX=8
Edge not reached: Edge: 'e_valid_Search', INDEX=16
Edge not reached: Edge: 'e_valid_Search', INDEX=17
Vertex not reached: Vertex: 'v_AboutURL', INDEX=4
Vertex not reached: Vertex: 'v_BaseURL', INDEX=2
Vertex not reached: Vertex: 'v_BrowserStarted', INDEX=1
Vertex not reached: Vertex: 'v_Faq', INDEX=5
Vertex not reached: Vertex: 'v_Search_regex_results', INDEX=6
Vertex not reached: Vertex: 'v_Search_valid_results', INDEX=7
Coverage Edges: 0/13 => 0%
Coverage Vertices: 1/7 => 14%
Unvisited Edges:  13
Unvisited Vertices: 6
Test sequence length:  0
Execution time: 3 seconds
2012-07-30 16:57:28,645 [main] INFO  - Done merging
2012-07-30 16:57:31,727 [Thread-0] INFO  - Edge not reached: Edge: 'e_AddBookToCart', INDEX=12
Edge not reached: Edge: 'e_ClickBook', INDEX=11
Edge not reached: Edge: 'e_EnterBaseURL', INDEX=9
Edge not reached: Edge: 'e_SearchBook', INDEX=10
Edge not reached: Edge: 'e_SearchBook', INDEX=16
Edge not reached: Edge: 'e_SearchBook', INDEX=17
Edge not reached: Edge: 'e_SearchBook', INDEX=18
Edge not reached: Edge: 'e_ShoppingCart', INDEX=13
Edge not reached: Edge: 'e_ShoppingCart', INDEX=14
Edge not reached: Edge: 'e_ShoppingCart', INDEX=15
Edge not reached: Edge: 'e_StartBrowser', INDEX=8
Vertex not reached: Vertex: 'v_BaseURL', INDEX=3
Vertex not reached: Vertex: 'v_BookInformation', INDEX=5
Vertex not reached: Vertex: 'v_BrowserStarted', INDEX=2
Vertex not reached: Vertex: 'v_OtherBoughtBooks', INDEX=6
Vertex not reached: Vertex: 'v_SearchResult', INDEX=4
Vertex not reached: Vertex: 'v_ShoppingCart', INDEX=7
Coverage Edges: 0/11 => 0%
Coverage Vertices: 1/7 => 14%
Unvisited Edges:  11
Unvisited Vertices: 6
Test sequence length:  0
Execution time: 3 seconds

**Comment by KristianKarl-zz** [comment]
Logger prints statistics when running sub-command 'source'. It should not do that.
To be fixed.

**Comment by KristianKarl-zz** [comment]
I'm not sure about you're problem description. 
1) Do not get any source code printed to std output at all?
2) The error you refer to, is that from the graphwalker.log file?

**Comment by invertednz** [comment]
Hi Kristian,

That error was from the graphwalker.log.  Thanks for clarifying.  I've managed to get the demo working.  It's a great tool that you've built, thanks for your help.

Regards,
James

**Comment by KristianKarl-zz** [comment]
Fixed by d18cf888d504756a7ec55849cbb7f9bf8ad3acac
